# Generated by Django 5.1.3 on 2024-11-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("SHIPPING", "Shipping Address"),
                            ("BILLING", "Billing Address"),
                        ],
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("street_address", models.CharField(max_length=255)),
                ("street_address2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("postcode", models.CharField(max_length=10)),
                ("country", models.CharField(default="United Kingdom", max_length=100)),
                ("place_id", models.CharField(blank=True, max_length=255)),
                ("formatted_address", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                "verbose_name_plural": "addresses",
                "ordering": ["-is_default", "-created"],
            },
        ),
    ]
