# Generated by Django 5.1.4 on 2024-12-11 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("SHIPPING", "Shipping Address"),
                            ("BILLING", "Billing Address"),
                        ],
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("street_address", models.CharField(max_length=255)),
                ("street_address2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("postcode", models.CharField(max_length=10)),
                ("country", models.CharField(default="United Kingdom", max_length=100)),
                ("place_id", models.CharField(blank=True, max_length=255)),
                ("formatted_address", models.CharField(blank=True, max_length=255)),
                ("latitude", models.CharField(blank=True, max_length=20, null=True)),
                ("longitude", models.CharField(blank=True, max_length=20, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "addresses",
                "ordering": ["-is_default", "-created"],
                "indexes": [
                    models.Index(
                        fields=["session_key"], name="addresses_a_session_8dddc2_idx"
                    ),
                    models.Index(
                        fields=["user"], name="addresses_a_user_id_b900c8_idx"
                    ),
                ],
            },
        ),
    ]
