# Generated by Django 5.1.3 on 2024-11-19 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["session_key"], name="addresses_a_session_8dddc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["user"], name="addresses_a_user_id_b900c8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={("user", "address_type", "is_default")},
        ),
    ]
