# Generated by Django 5.1.3 on 2024-11-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
