# Generated by Django 5.1.5 on 2025-01-25 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChocolateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LayerColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("hex_code", models.CharField(blank=True, max_length=7, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LayerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChocolateLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "top_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="chocolates/top/"
                    ),
                ),
                (
                    "side_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="chocolates/side/"
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personalized.layercolor",
                    ),
                ),
                (
                    "layer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personalized.layertype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateLayerSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Label for this slot",
                        max_length=120,
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "layer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personalized.layertype",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personalized.chocolatetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="chocolatetemplate",
            name="layer_slots",
            field=models.ManyToManyField(
                related_name="templates",
                through="personalized.TemplateLayerSlot",
                to="personalized.layertype",
            ),
        ),
        migrations.CreateModel(
            name="UserChocolateDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personalized.chocolatetemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserChosenLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "chocolate_layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personalized.chocolatelayer",
                    ),
                ),
                (
                    "user_design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="personalized.userchocolatedesign",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="userchocolatedesign",
            name="chosen_layers",
            field=models.ManyToManyField(
                related_name="user_designs",
                through="personalized.UserChosenLayer",
                to="personalized.chocolatelayer",
            ),
        ),
    ]
