version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: 071222593443.dkr.ecr.eu-west-2.amazonaws.com/django-casspea:web
    command: gunicorn erp.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.staging

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    image: 071222593443.dkr.ecr.eu-west-2.amazonaws.com/django-casspea:nginx-proxy
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web

  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.staging.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  certs:
  html:
  acme:
