# Generated by Django 5.1.3 on 2024-11-19 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("allergens", "0001_initial"),
        ("carts", "0001_initial"),
        ("flavours", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="carts.cart",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="cartitemboxcustomization",
            name="allergens",
            field=models.ManyToManyField(blank=True, to="allergens.allergen"),
        ),
        migrations.AddField(
            model_name="cartitemboxcustomization",
            name="cart_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_customization",
                to="carts.cartitem",
            ),
        ),
        migrations.AddField(
            model_name="cartitemboxflavorselection",
            name="box_customization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flavor_selections",
                to="carts.cartitemboxcustomization",
            ),
        ),
        migrations.AddField(
            model_name="cartitemboxflavorselection",
            name="flavor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flavours.flavour"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["session_id"], name="carts_cart_session_846cdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "product"], name="carts_carti_cart_id_8f3e40_idx"
            ),
        ),
    ]
