# Generated by Django 5.1.3 on 2024-11-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitemboxcustomization_cartitemboxflavorselection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
