# Generated by Django 5.1.3 on 2024-11-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_discount_cartitem_created_cartitem_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gift_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
