# Generated by Django 5.1.3 on 2024-11-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_gift_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
