# Generated by Django 5.1.3 on 2024-11-30 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="shipping_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.shippingoption",
            ),
        ),
    ]
