# Generated by Django 5.1.4 on 2024-12-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_alter_checkoutsession_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
