# Generated by Django 5.1.3 on 2024-11-19 17:07

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("allergens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlavourCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Flavour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("mini_description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Main product image",
                        null=True,
                        storage=storages.backends.s3.S3Storage(location="media"),
                        upload_to="flavours",
                    ),
                ),
                (
                    "image_webp",
                    models.ImageField(
                        blank=True,
                        help_text="WebP version of main image",
                        null=True,
                        upload_to="flavours/images/%Y/%m/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image (JPEG)",
                        null=True,
                        upload_to="flavours/thumbnails/%Y/%m/",
                    ),
                ),
                (
                    "thumbnail_webp",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image (WebP)",
                        null=True,
                        upload_to="flavours/thumbnails/%Y/%m/",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("allergens", models.ManyToManyField(to="allergens.allergen")),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flavours.flavourcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlavourSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "flavour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flavours.flavour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlavourBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("selections", models.ManyToManyField(to="flavours.flavourselection")),
            ],
        ),
    ]
