# Generated by Django 5.1.3 on 2024-11-10 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flavours.flavourcategory'),
        ),
        migrations.AddField(
            model_name='flavourcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
