# Generated by Django 5.1.4 on 2025-01-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flavours", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flavour",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="flavour",
            name="image_webp",
        ),
        migrations.RemoveField(
            model_name="flavour",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="flavour",
            name="thumbnail_webp",
        ),
    ]
