# Generated by Django 5.1.3 on 2024-11-15 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavours', '0002_flavour_category_flavourcategory_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='image_webp',
            field=models.ImageField(blank=True, help_text='WebP version of main image', null=True, upload_to='flavours/images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='flavour',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image (JPEG)', null=True, upload_to='flavours/thumbnails/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='flavour',
            name='thumbnail_webp',
            field=models.ImageField(blank=True, help_text='Thumbnail image (WebP)', null=True, upload_to='flavours/thumbnails/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='flavours/images/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='FlavourSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flavours.flavour')),
            ],
        ),
        migrations.CreateModel(
            name='FlavourBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('selections', models.ManyToManyField(to='flavours.flavourselection')),
            ],
        ),
    ]
