# Generated by Django 5.1.3 on 2024-11-17 17:53

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavours', '0003_flavour_image_webp_flavour_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, storage=storages.backends.s3.S3Storage(location='media'), upload_to='flavours'),
        ),
    ]
