# Generated by Django 5.1.4 on 2025-01-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingoption",
            name="service_code",
            field=models.CharField(max_length=50, unique=True, null=True, blank=True),
        ),
    ]
