# Generated by Django 5.1.4 on 2025-01-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_shippingoption_service_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingoption",
            name="service_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
