# Generated by Django 5.1.5 on 2025-01-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0003_alter_shippingoption_service_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingoption",
            options={"ordering": ["price"]},
        ),
    ]
