# Generated by Django 5.1.3 on 2024-11-19 23:36

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default=orders.models.generate_order_id,
                editable=False,
                max_length=100,
                unique=True,
            ),
        ),
    ]
