# Generated by Django 5.1.4 on 2025-01-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="box_weight",
            field=models.IntegerField(
                default=150, help_text="Weight of the box in grams"
            ),
        ),
    ]
