# Generated by Django 5.1.3 on 2024-11-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units_per_box',
            field=models.IntegerField(help_text='Number of chocolates in the box'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(help_text='Weight in grams'),
        ),
    ]
