# Generated by Django 5.1.3 on 2024-11-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-base_price"]},
        ),
    ]
