# Generated by Django 5.1.4 on 2024-12-08 14:56

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Gallery image",
                        storage=storages.backends.s3.S3Storage(location="media"),
                        upload_to="products/gallery/%Y/%m/",
                    ),
                ),
                (
                    "image_webp",
                    models.ImageField(
                        blank=True,
                        help_text="WebP version of gallery image",
                        null=True,
                        storage=storages.backends.s3.S3Storage(location="media"),
                        upload_to="products/gallery/%Y/%m/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image (JPEG)",
                        null=True,
                        storage=storages.backends.s3.S3Storage(location="media"),
                        upload_to="products/gallery/thumbnails/%Y/%m/",
                    ),
                ),
                (
                    "thumbnail_webp",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image (WebP)",
                        null=True,
                        storage=storages.backends.s3.S3Storage(location="media"),
                        upload_to="products/gallery/thumbnails/%Y/%m/",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for image",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of images in gallery"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created"],
                "unique_together": {("product", "order")},
            },
        ),
    ]
