# Generated by Django 5.1.3 on 2024-11-17 17:53

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_units_per_box_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, storage=storages.backends.s3.S3Storage(location='media'), upload_to='flavours'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_webp',
            field=models.ImageField(blank=True, help_text='WebP version of main image', null=True, upload_to='products/images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image (JPEG)', null=True, upload_to='products/thumbnails/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_webp',
            field=models.ImageField(blank=True, help_text='Thumbnail image (WebP)', null=True, upload_to='products/thumbnails/%Y/%m/'),
        ),
    ]
