# Generated by Django 5.1.5 on 2025-01-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_box_weight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["base_price"]},
        ),
    ]
